# Site settings
title: Programming Tutorials
description: this is a place where I've compiled my work to build on-boarding tutorials
baseurl: "/tutorials" # the subpath of your site, e.g. /blog
url: "https://alexbgurvi.ch" # the base hostname & protocol for your site e.g. http://alexbgurvi.ch
destination: docs

safe: false

# User settings
username: happy
user_description: Frick
email: anon@anon.com
#twitter_username: lorem_ipsum
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

collections: 
  my_categories:
    output: false

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

defaults:
  - scope:
      type: categories  # select all category pages
    values:
      layout: category_page
      permalink: categories/:category/